language: php
before_script: composer install
php:
  - '7.1'
  - '7.2'
  - nightly

script:
  - mkdir -p build/logs
  - composer run code-sniffer
  - composer run test
  - composer run static-analysis
  - composer run mess-detector

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
